name: Gradle Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew build

      - uses: codecov/codecov-action@v1.2.1

      ### PUBLISHING STEPS ###

      - name: Get publishing variables
        id: publish_vars
        uses: enonic/release-tools/publish-vars@master
        env:
          PROPERTIES_PATH: './gradle.properties'
          JAVA_HOME: ''

      - name: Download changelog
        if: steps.publish_vars.outputs.release == 'true'
        uses: actions/download-artifact@v2
        with:
          name: changelog

      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./gradlew publish -PrepoKey=${{ steps.publish_vars.outputs.repo }} -PrepoUser=${{ secrets.ARTIFACTORY_USERNAME }} -PrepoPassword=${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Create Release
        if: steps.publish_vars.outputs.release == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.publish_vars.outputs.tag_name }}
          body_path: changelog.md
          release_name: Rewrite App ${{ steps.publish_vars.outputs.version }}
          prerelease: ${{ steps.publish_vars.outputs.prerelease == 'true' }}

      - name: Write new snapshot version
        if: steps.publish_vars.outputs.release == 'true'
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'version'
          value: ${{ steps.publish_vars.outputs.nextSnapshot }}

      - name: Commit and push new version
        if: steps.publish_vars.outputs.release == 'true'
        uses: EndBug/add-and-commit@v6.2.0
        with:
          add: ./gradle.properties
          message: 'Updated to next SNAPSHOT version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
